### ISSUE TITLE
Please tell me, what's wrong with my .gitattributes 

### ISSUE THREAD

**Issue by F3ns** [atikhono/defaultreviewers#8]
Arm_xml/ owners=a.nelzin 

Arm_xml - this is a directory
a.nelzin  - this is username of bitbucket user

**Comment by atikhono** [comment]
Hi,
I can't tell what's wrong with it unless you tell me 1) what you expect, 2) what you actually get.
Please provide a related exception from bitbucket.log, if you see an issue in the plugin.

**Comment by F3ns** [comment]
I want to add a.nelzin  default reviewer to bitbucket pull-request, when pull-request to repository Arm_xml

**Comment by atikhono** [comment]
`* owners=a.nelzin`
or use Bitbucket's "Default Reviewers" built-in functionality.

**Comment by F3ns** [comment]
Sorry I want to say  Arm_xml this is a path in repository 

Arm_xml/* owners=a.nelzin        right?

Я установил плагин и создал в корне файл .gitattributes, там прописал данную строчку, для того, чтобы a.nelzin добавлялся каждый раз в ревьюеры, когда в папку arm_xml  будут менять посредством пул-реквеста.
